### ISSUE TITLE
Can we lose comment in timetable use case?

### ISSUE THREAD

**Issue by peteyak** [nsip/usecases#5]
In this HITS how-to use case:
https://github.com/nsip/usecases/blob/master/docs/timetable/howto.md
there is the following comment (ll116-120):
``

Can we confirm yes or no and get rid of it? It's the only outstanding comment in the use cases, and I'm not sure how it will convert to HTML/Word (ie if it will stay hidden or get stripped.) This raises another issue but that's another issue...

**Comment by opoudjis** [comment]
List of calls being generated automatically? No, we don't have that sophisticated an API, and even if we did, we would still need to edit it (some objects may be redundant, for example). Delete the comment, we'll manually populate each list.

**Comment by peteyak** [comment]
Fixed
